{% set name = "grass" %}
{% set version = "7.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://grass.osgeo.org/grass72/source/grass-7.2.2RC1.tar.gz
  patches:
    - platform.make.in.patch [osx]
    - platform.make.in-linux.patch [linux]
    - loader.py.patch
    - rules.make.patch [osx]
    - rules.make.patch [linux]
    - aclocal.m4.patch
    - configure.patch
    - install.make.patch

requirements:
  build:
    - python
    - setuptools
    - numpy
    - gdal
    - freetype
    - cairo
    - matplotlib
    - pandoc
    - pil
    - wxpython
    - sqlite
    - jpeg
    - libpng
    - libtiff
    - pkg-config [osx]
    - libiconv
    - fftw
    - blas
    - giflib
    - python.app [osx]

  run:
    - python
    - setuptools
    - numpy
    - gdal
    - freetype
    - cairo
    - matplotlib
    - pandoc
    - pil
    - wxpython
    - sqlite
    - jpeg
    - libpng
    - libtiff
    - pkg-config [osx]
    - libiconv
    - fftw
    - blas
    - giflib
    - python.app [osx]

build:
  number: 0

about:
  summary: Geographic Resources Analysis Support System
  description: |
    GRASS GIS, commonly referred to as GRASS (Geographic Resources
    Analysis Support System), is a free and open source Geographic
    Information System (GIS) software suite used for geospatial data
    management and analysis, image processing, graphics and maps
    production, spatial modeling, and visualization.
  home: https://grass.osgeo.org/
  license: GPLv2
  dev_url: https://grass.osgeo.org/development/

