language: generic
os:
# - linux
- osx
env:
  global:
  - PREFIX=$HOME/grass
  - MACOSX_DEPLOYMENT_TARGET="10.9"
  - GRASS_SVN_REPO="https://svn.osgeo.org/grass/grass"
  - GRASS_SOURCE_URL="https://grass.osgeo.org/grass72/source"
  - GRASS_PYTHON=pythonw
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda2-latest"
  - TRAVIS_PYTHON_VERSION="2.7"
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
    REQUIREMENTS=requirements.txt
  else
    OS="Linux-x86_64"
    REQUIREMENTS=requirements-linux.txt
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $PREFIX
- export PATH="$PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install python=$TRAVIS_PYTHON_VERSION
- conda install --file=$REQUIREMENTS -c noaa-orr-erd -c defaults -c conda-forge
- conda list
- conda info -a
script:
- curl $GRASS_SOURCE_URL/grass-7.2.2RC1.tar.gz > grass-7.2.2.tar.gz
- tar xfz grass-7.2.2.tar.gz
- mv grass-7.2.2RC1 grass-7.2.2
- patch -p0 < platform.make.in.patch
- patch -p0 < loader.py.patch
- patch -p0 < rules.make.patch
- patch -p0 < aclocal.m4.patch
- patch -p0 < install.make.patch
- patch -p0 < configure.patch
- cd grass-7.2.2
- travis_wait 40 bash ../recipe/build.sh
- make -j4 install
